"use client";

import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";

interface HealthScoreProps {
  healthScore: number;
  riskLabel: string;
  sentimentScore?: number;
  operationalStatus?: string;
  summaryPoints?: string[];
  synergyMatches?: { name: string; reason: string; score: number }[];
}

export function HealthScoreCard({
  healthScore,
  riskLabel,
  sentimentScore,
  operationalStatus,
  summaryPoints,
  synergyMatches,
}: HealthScoreProps) {
  const getRiskColor = (label: string) => {
    switch (label) {
      case "HIGH_GROWTH":
        return { badge: "bg-emerald-500/10 text-emerald-400 border-emerald-500/20", bar: "bg-emerald-500" };
      case "STABLE":
        return { badge: "bg-blue-500/10 text-blue-400 border-blue-500/20", bar: "bg-blue-500" };
      case "AT_RISK":
        return { badge: "bg-red-500/10 text-red-400 border-red-500/20", bar: "bg-red-500" };
      default:
        return { badge: "bg-slate-500/10 text-slate-400 border-slate-500/20", bar: "bg-slate-500" };
    }
  };

  const riskColor = getRiskColor(riskLabel);
  const displayLabel = riskLabel === "HIGH_GROWTH" ? "High Growth" : riskLabel === "AT_RISK" ? "At Risk" : riskLabel;

  return (
    <div className="space-y-6">
      <Card className="bg-slate-900 border-slate-800">
        <CardHeader>
          <div className="flex items-center justify-between">
            <CardTitle className="text-white text-lg">AI Health Evaluation</CardTitle>
            <Badge variant="outline" className={riskColor.badge}>
              {displayLabel}
            </Badge>
          </div>
        </CardHeader>
        <CardContent className="space-y-6">
          <div className="space-y-2">
            <div className="flex items-center justify-between text-sm">
              <span className="text-slate-400">Health Score</span>
              <span className="text-white font-bold text-2xl">{healthScore}<span className="text-slate-500 text-sm font-normal">/100</span></span>
            </div>
            <div className="h-3 rounded-full bg-slate-800 overflow-hidden">
              <div
                className={`h-3 rounded-full transition-all duration-500 ${riskColor.bar}`}
                style={{ width: `${healthScore}%` }}
              />
            </div>
          </div>

          <div className="grid gap-4 sm:grid-cols-2">
            {sentimentScore !== undefined && (
              <div className="rounded-lg bg-slate-800/50 p-4">
                <p className="text-xs text-slate-500 mb-1">Sentiment Score</p>
                <p className="text-lg font-semibold text-white">{(sentimentScore * 100).toFixed(0)}%</p>
              </div>
            )}
            {operationalStatus && (
              <div className="rounded-lg bg-slate-800/50 p-4">
                <p className="text-xs text-slate-500 mb-1">Operational Status</p>
                <p className="text-sm text-slate-300">{operationalStatus}</p>
              </div>
            )}
          </div>
        </CardContent>
      </Card>

      {summaryPoints && summaryPoints.length > 0 && (
        <Card className="bg-slate-900 border-slate-800">
          <CardHeader>
            <CardTitle className="text-white text-lg">Executive Summary</CardTitle>
          </CardHeader>
          <CardContent>
            <ul className="space-y-3">
              {summaryPoints.map((point, i) => (
                <li key={i} className="flex gap-3 text-sm text-slate-300">
                  <span className="flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-cyan-500/10 text-cyan-400 text-xs font-bold">
                    {i + 1}
                  </span>
                  {point}
                </li>
              ))}
            </ul>
            <p className="text-xs text-slate-600 mt-4">Generated by AI · Gemini 1.5 Flash via OpenRouter</p>
          </CardContent>
        </Card>
      )}

      {synergyMatches && synergyMatches.length > 0 && (
        <Card className="bg-slate-900 border-slate-800">
          <CardHeader>
            <CardTitle className="text-white text-lg">Synergy Recommendations</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="space-y-3">
              {synergyMatches.map((match, i) => (
                <div key={i} className="rounded-lg border border-slate-800 bg-slate-800/30 p-4">
                  <div className="flex items-center justify-between mb-2">
                    <p className="font-medium text-white">{match.name}</p>
                    <Badge variant="outline" className="bg-cyan-500/10 text-cyan-400 border-cyan-500/20">
                      {Math.round(match.score * 100)}% match
                    </Badge>
                  </div>
                  <p className="text-sm text-slate-400">{match.reason}</p>
                </div>
              ))}
            </div>
            <p className="text-xs text-slate-600 mt-4">Generated by AI · Gemini 1.5 Flash via OpenRouter</p>
          </CardContent>
        </Card>
      )}
    </div>
  );
}

export function ScoreGauge({ score, size = "md" }: { score: number; size?: "sm" | "md" | "lg" }) {
  const getColor = (s: number) => {
    if (s >= 70) return "stroke-emerald-500";
    if (s >= 40) return "stroke-blue-500";
    return "stroke-red-500";
  };
  const getLabel = (s: number) => {
    if (s >= 70) return "Healthy";
    if (s >= 40) return "Stable";
    return "At Risk";
  };

  const dimensions = size === "sm" ? 80 : size === "lg" ? 160 : 120;
  const strokeWidth = size === "sm" ? 6 : size === "lg" ? 12 : 8;
  const radius = (dimensions - strokeWidth) / 2;
  const circumference = 2 * Math.PI * radius;
  const offset = circumference - (score / 100) * circumference;

  return (
    <div className="flex flex-col items-center gap-1">
      <svg width={dimensions} height={dimensions} className="-rotate-90">
        <circle
          cx={dimensions / 2}
          cy={dimensions / 2}
          r={radius}
          fill="none"
          stroke="currentColor"
          strokeWidth={strokeWidth}
          className="text-slate-800"
        />
        <circle
          cx={dimensions / 2}
          cy={dimensions / 2}
          r={radius}
          fill="none"
          stroke="currentColor"
          strokeWidth={strokeWidth}
          strokeDasharray={circumference}
          strokeDashoffset={offset}
          strokeLinecap="round"
          className={`${getColor(score)} transition-all duration-1000`}
        />
      </svg>
      <span className={`font-bold ${size === "lg" ? "text-3xl" : size === "sm" ? "text-sm" : "text-xl"} text-white`}>
        {score}
      </span>
      <span className={`${size === "sm" ? "text-[10px]" : "text-xs"} text-slate-500`}>{getLabel(score)}</span>
    </div>
  );
}
